services:
  # 🗄️ Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: plataforma-tag-postgres
    environment:
      POSTGRES_DB: tag_financeiro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - plataforma-tag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🔴 Cache Redis
  redis:
    image: redis:7-alpine
    container_name: plataforma-tag-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - plataforma-tag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🐍 Backend Python/FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: plataforma-tag-backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tag_financeiro
      - REDIS_URL=redis://redis:6379
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=True
      - JWT_SECRET_KEY=sua_chave_secreta_aqui_muito_segura
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - plataforma-tag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # ⚛️ Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plataforma-tag-frontend
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_APP_NAME=Plataforma TAG
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - plataforma-tag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: npm run dev

  # 🌐 Nginx (Proxy Reverso - Opcional)
  nginx:
    image: nginx:alpine
    container_name: plataforma-tag-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - plataforma-tag-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  backend_uploads:
    driver: local
  backend_logs:
    driver: local

networks:
  plataforma-tag-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

