# Render Configuration
services:
  - type: web
    name: plataforma-tag-backend
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plataforma-tag-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: plataforma-tag-redis
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: JWT_REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://seu-frontend.vercel.app,https://plataforma-tag.com

databases:
  - name: plataforma-tag-postgres
    databaseName: tag_financeiro
    user: postgres
    plan: basic

  - name: plataforma-tag-redis
    plan: basic
